### ISSUE TITLE
copyModelStateDict: Unknown state dict entry 'pi3.weight' -- could not find parameter/buffer 'weight'

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [facebookincubator/Polygames#10]
## Steps to reproduce

1. Install Pytorch 1.2.0 and Polygames based on the instructions given in the README adapted for our cluster (https://github.com/facebookincubator/Polygames#first-install-conda-and-pytorch).
2. Run `python -m pypolygames train --game_name Hex11`

## Observed Results

```
######################################################################
#                              TRAINING                              #
######################################################################
setting-up pseudo-random generator...
creating and saving the model...
creating a generic model
total #trainable params = 3218050
creating optimizer...
creating training environment...
Game generation devices: ['cuda:0']
is_server is  False
is_client is  False
 -- UPDATE MODEL --
copyModelStateDict: Unknown state dict entry 'pi3.weight' -- could not find parameter/buffer 'weight'
Aborted
```

Note:
* The error is the same if I force using the CPU with `--device cpu`.
* The error is similar if I change the model (e.g. `copyModelStateDict: Unknown state dict entry 'pi_logit.weight' -- could not find parameter/buffer 'weight'`).

**Comment by RemiLacroix-IDRIS** [comment]
@juliendehos: Sorry to ping you directly but I am not sure if you are notified of new issue and if you check them regularly. Any pointers regarding this issue would be greatly appreciated.

**Comment by juliendehos** [comment]
@RemiLacroix-IDRIS Thank you for reporting this issue. I'm trying to reproduce the problem on a new installation. Can you give some details about your system (OS, GPU model)? Did you use Modules?

**Comment by RemiLacroix-IDRIS** [comment]
The OS is Red Hat Enterprise Linux Server release 7.6 and we have 4 NVIDIA V100 GPUs per node.

Also yes, we are using Modules.

**Comment by juliendehos** [comment]
Maybe this OS is too old. Unfortunately, I have no similar system to try.
Can you try with a more recent system ?
Alternatively, if you can use Nix on your system, you can try this: https://github.com/juliendehos/Polygames/tree/nix/nix

**Comment by RemiLacroix-IDRIS** [comment]
I can compile Pytorch and Polygames without any error so I'm not sure if the OS can really be the problem.

I just tried the compilation without modules, using Pytorch 1.2.0 from Conda as described here: https://github.com/facebookincubator/Polygames#compilation-guide-without-modules but I have the same error at runtime.

**Comment by kimchitsigai** [comment]
Hi,
I have the same issue. 
It seems to me that Polygames code is designed to run on the pre-1.2 PyTorch versions. 
The TorchScript relevant code in generic_model.py, for instance, is written for PyTorch 1.1, but isn't it deprecated wrt PyTorch >= 1.2 ? 
Thanks.

**Comment by juliendehos** [comment]
Polygames can be run on the 1.2 PyTorch version, using `cmake -DPYTORCH12=ON ..`.
I personally use this version, and the method described here: https://github.com/facebookincubator/Polygames/tree/master/nix .
@kimchitsigai Is it RHEL7 too ?

**Comment by RemiLacroix-IDRIS** [comment]
Turns out the problem was just a programming error which weirdly enough has no impact for you. I have provided a PR (#19) that fixes this issue.
