### ISSUE TITLE
Won't CMake with VS 

### ISSUE THREAD

**Issue by EngrStudent** [facebookincubator/Polygames#28]
## Steps to reproduce

  1. Don't have Visual Studio (or any c-compiler) installed
  2. Have Anaconda 
  3. Follow steps for "compilation without modules"

## Observed Results

  * CMake Error at line 60    
I installed visual studio community, with cmake, and windows api, allegedly for c/c++ development on windows.  I then try to run cmake, and it gives errors.  So I find this (https://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=vs-2019) and try to follow it to cmake.  In both cases I get this error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at .../Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    ".../Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: .../Polygames/out/build/x64-Debug/CMakeFiles/CMakeTmp
    
    Run Build Command(s):.../Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_c6e64 && [1/2] Building C object CMakeFiles\cmTC_c6e64.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_c6e64.exe
    FAILED: cmTC_c6e64.exe 
    cmd.exe /C "cd . && "...\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_c6e64.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- "...\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\bin\Hostx64\x64\link.exe" /nologo CMakeFiles\cmTC_c6e64.dir\testCCompiler.c.obj  /out:cmTC_c6e64.exe /implib:cmTC_c6e64.lib /pdb:cmTC_c6e64.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_c6e64.dir/manifest.res CMakeFiles\cmTC_c6e64.dir/manifest.rc" failed (exit code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.		.../Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.17/Modules/CMakeTestCCompiler.cmake	60	

## Expected Results

  * What did you expect to happen?
  I expected it to build so I could then make it and then run it.

## Relevant Code

  ```
  git clone ... 
cd polygames
mkdir build
cd build
cmake .. [gcc>=7]
make
  ```

**Comment by tscmoo** [comment]
Building on Windows(/Visual Studio) is currently not supported, sorry!
