### ISSUE TITLE
Using pytorch 1.5 fails with "undefined symbol: THPVariableClass" 

### ISSUE THREAD

**Issue by reidsanders** [facebookincubator/Polygames#40]
## Steps to reproduce

1. install exactly as non devfair instructions, except instead of
  > conda install pytorch=1.1.0 cuda92 -c pytorch 
  
run:
  > conda install pytorch=1.5 cuda100 -c pytorch
  
Then build as usual except use:
  > cmake -DPYTORCH15=ON ..
  
Then run connect4 test with:
  > python -m pypolygames train --game_name="Connect4"

## Observed Results
Fails with:
$ python -m pypolygames train --game_name="Connect4" --num_games 4
Traceback (most recent call last):
  File "/home/rs/mirror/anaconda3/envs/polygames4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rs/mirror/anaconda3/envs/polygames4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rs/crypt/rl/polygames3/pypolygames/__main__.py", line 24, in <module>
    from .utils import CommandHistory
  File "/home/rs/crypt/rl/polygames3/pypolygames/utils/__init__.py", line 6, in <module>
    from .checkpoint import Checkpoint, save_checkpoint, load_checkpoint, gen_checkpoints
  File "/home/rs/crypt/rl/polygames3/pypolygames/utils/checkpoint.py", line 16, in <module>
    import tube
ImportError: /home/rs/crypt/rl/polygames3/build/torchRL/tube/tube.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

## Expected Results

Standard training. Pytorch 1.1 does work as expected.

## Attempted Fixes:
Tried all variations of PYTORCH15 PYTORCH12 flags
Tried different pytorch-magma100 pytorch-magma102 versions. tried cuda92, cuda100 (there is no cuda102)
Tried 71a6 commit where pytorch 1.5 support was officially added.

g++ (GCC) 10.1.0

conda list:

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
blas                      2.16                        mkl    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
cmake                     3.17.0               h28c56e5_0    conda-forge
cudatoolkit               10.2.89              hfd86e86_1  
expat                     2.2.9                he1b5a44_2    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
idna                      2.10                     pypi_0    pypi
intel-openmp              2020.1                      217  
jpeg                      9d                   h516909a_0    conda-forge
jsonpatch                 1.26                     pypi_0    pypi
jsonpointer               2.0                      pypi_0    pypi
krb5                      1.17.1               hfafb76e_1    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_7    conda-forge
libblas                   3.8.0                    16_mkl    conda-forge
libcblas                  3.8.0                    16_mkl    conda-forge
libcurl                   7.71.1               hcdd3856_2    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0                    16_mkl    conda-forge
liblapacke                3.8.0                    16_mkl    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_2    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libprotobuf               3.12.3               h8b12597_1    conda-forge
libssh2                   1.9.0                hab1572f_4    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuv                     1.38.0               h516909a_0    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
magma-cuda100             2.5.2                         1    pytorch
magma-cuda102             2.5.2                         1    pytorch
mkl                       2020.1                      217  
mkl-include               2020.1                      219    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
ninja                     1.10.0               hc9558a2_0    conda-forge
numpy                     1.19.0           py37h8960a57_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pillow                    7.2.0            py37h718be6c_1    conda-forge
pip                       20.1.1                     py_1    conda-forge
protobuf                  3.12.3           py37h3340039_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
python                    3.7.6           cpython_h8356626_6    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.5.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
pyzmq                     19.0.1                   pypi_0    pypi
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0                   pypi_0    pypi
rhash                     1.3.6             h14c3975_1001    conda-forge
scipy                     1.5.1                    pypi_0    pypi
setuptools                49.2.0           py37hc8dfbb8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
tensorboardx              2.1                        py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
torchfile                 0.1.0                    pypi_0    pypi
torchvision               0.6.1                py37_cu102    pytorch
tornado                   6.0.4                    pypi_0    pypi
typing                    3.7.4.3          py37hc8dfbb8_0    conda-forge
urllib3                   1.25.9                   pypi_0    pypi
visdom                    0.1.8.9                  pypi_0    pypi
websocket-client          0.57.0                   pypi_0    pypi
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.5                h6597ccf_1    conda-forge

I'd much prefer to work in the up to date pytorch, but I can only find one other reference to this error: 
https://github.com/pytorch/extension-cpp/issues/6 , which is old and doesn't seem to provide any relevant solution. Thanks!

**Comment by heiner** [comment]
I suspect the underlying error is https://github.com/pytorch/pytorch/issues/38122. You can check by running this with `TORCH_USE_RTLD_GLOBAL=YES`.

**Comment by reidsanders** [comment]
Thanks heiner. I made a pull request to fix as per that issue.

**Comment by tscmoo** [comment]
Fixed in #42
