### ISSUE TITLE
missing "internal" test ?

### ISSUE THREAD

**Issue by juliendehos** [facebookincubator/Polygames#6]
`.github/CONTRIBUTING.md` suggests "testing the python tools" but it seems there is no such test.

## Steps to reproduce

```
pytest internal pypolygames --durations=10 --verbose
```

## Observed Results

```
=========================================================================== no tests ran in 0.00s ===========================================================================
ERROR: file not found: internal
```

**Comment by jrapin** [comment]
`internal` has been removed indeed, so we need to update the doc and remove it there as well
